-- FORMATIVA SEMANA 5

-- CASO 1:

SELECT
    TO_CHAR(c.NUMRUN, '999G999G999') || '-' || c.DVRUN AS "RUT Cliente",
    INITCAP(c.PNOMBRE) || ' ' || INITCAP(c.APPATERNO) AS "Nombre Cliente",
    UPPER(p.NOMBRE_PROF_OFIC) AS "Profesión Cliente",
    TO_CHAR(c.FECHA_INSCRIPCION, 'DD-MM-YYYY') AS "Fecha de Inscripción",
    c.DIRECCION AS "Dirección Cliente" 
FROM CLIENTE c    
INNER JOIN PROFESION_OFICIO p ON c.COD_PROF_OFIC = p.COD_PROF_OFIC  
WHERE p.NOMBRE_PROF_OFIC IN ('Contador', 'Vendedor')
AND (EXTRACT(YEAR FROM c.FECHA_INSCRIPCION) > 
    (SELECT
        ROUND(AVG((EXTRACT(YEAR FROM c.FECHA_INSCRIPCION))))
        FROM CLIENTE c
        INNER JOIN PROFESION_OFICIO p ON c.COD_PROF_OFIC = p.COD_PROF_OFIC
        WHERE p.NOMBRE_PROF_OFIC IN ('Contador', 'Vendedor')))
ORDER BY TO_CHAR(c.NUMRUN, '999G999G999') || '-' || c.DVRUN;

-- CASO 2:
CREATE TABLE CLIENTES_CUPOS_COMPRAS AS
SELECT
    CONCAT(c.NUMRUN,CONCAT('-', UPPER(c.DVRUN)))  AS "RUT_CLIENTE",
    TRUNC((MONTHS_BETWEEN(SYSDATE, c.FECHA_NACIMIENTO))/12) AS "EDAD",
    TO_CHAR(t.CUPO_DISP_COMPRA, '$999G999G999') AS "CUPO_DISPONIBLE_COMPRA",
    UPPER(tc.NOMBRE_TIPO_CLIENTE) AS "TIPO_CLIENTE"
FROM CLIENTE c
INNER JOIN TARJETA_CLIENTE t ON c.NUMRUN = t.NUMRUN
INNER JOIN TIPO_CLIENTE tc ON c.COD_TIPO_CLIENTE = tc.COD_TIPO_CLIENTE
WHERE t.CUPO_DISP_COMPRA >=(
    SELECT 
        MAX(CUPO_DISP_COMPRA) 
        FROM TARJETA_CLIENTE t2
        INNER JOIN TRANSACCION_TARJETA_CLIENTE ttc ON  ttc.NRO_TARJETA = t2.NRO_TARJETA
        WHERE EXTRACT(YEAR FROM FECHA_TRANSACCION) = (EXTRACT(YEAR FROM SYSDATE) -1)
        )
ORDER BY TRUNC((MONTHS_BETWEEN(SYSDATE, c.FECHA_NACIMIENTO))/12);

SELECT * FROM CLIENTES_CUPOS_COMPRAS;


